### ISSUE TITLE
500

### ISSUE THREAD

**Issue by Zak-Adelman** [Volvagia356/pixiv-downloader#1]
I keep getting a "HTTP Error 500: Internal Server Error" when using the script.  It is finding the images (see partial log) but the error shows up on every single one of them and it won't download them.

LOG:
pixivdl.py 8981 ~/Desktop/Gofu
pixiv Downloader (C) 2013 Volvagia356

Downloading 37610710.jpg
HTTP Error 500: Internal Server Error
http://i2.pixiv.net/img1/img/gofu/37610710.jpg
Downloading 37528283.jpg
HTTP Error 500: Internal Server Error
http://i1.pixiv.net/img1/img/gofu/37528283.jpg
Downloading 37458160.jpg
etc...

**Comment by Volvagia356** [comment]
Looks like the number for the imgXX directory in the URL requires leading zeroes. Incoming fix.
